ALTER TABLE sprints ALTER COLUMN activo DROP NOT NULL;

--DELETE CASCADE
ALTER TABLE public.USUARIO_PROYECTO DROP CONSTRAINT proyectos_usuario_proyecto_fk;
ALTER TABLE public.SPRINTS DROP CONSTRAINT proyectos_sprints_fk;
ALTER TABLE public.US DROP CONSTRAINT proyectos_us_fk;
ALTER TABLE public.US DROP CONSTRAINT sprints_us_fk;
ALTER TABLE public.ROL_PERMISO DROP CONSTRAINT roles_rol_permiso_fk;
ALTER TABLE public.USUARIOS_ROLES DROP CONSTRAINT roles_usuarios_roles_fk;
ALTER TABLE public.ROL_PERMISO DROP CONSTRAINT permisos_rol_permiso_fk;

ALTER TABLE public.USUARIO_PROYECTO ADD CONSTRAINT proyectos_usuario_proyecto_fk
FOREIGN KEY (id_proyecto)
REFERENCES public.PROYECTOS (id_proyecto)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.SPRINTS ADD CONSTRAINT proyectos_sprints_fk
FOREIGN KEY (id_proyecto)
REFERENCES public.PROYECTOS (id_proyecto)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.US ADD CONSTRAINT proyectos_us_fk
FOREIGN KEY (id_proyecto)
REFERENCES public.PROYECTOS (id_proyecto)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.US ADD CONSTRAINT sprints_us_fk
FOREIGN KEY (id_sprint)
REFERENCES public.SPRINTS (id_sprint)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ROL_PERMISO ADD CONSTRAINT roles_rol_permiso_fk
FOREIGN KEY (id_rol)
REFERENCES public.ROLES (id_rol)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.USUARIOS_ROLES ADD CONSTRAINT roles_usuarios_roles_fk
FOREIGN KEY (id_rol)
REFERENCES public.ROLES (id_rol)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ROL_PERMISO ADD CONSTRAINT permisos_rol_permiso_fk
FOREIGN KEY (id_permiso)
REFERENCES public.PERMISOS (id_permiso)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;